### ISSUE TITLE
Camera Image is not showing.

### ISSUE THREAD

**Issue by SagarGang** [NileshJarad/ImagePicker#2]
When i click on show button and choose camera option to get the image .After taking the picture the image is not shown in the  Image View  (preview).But when i choose picture from Gallery it shows the Image in the Image View.

Device :- Motorola XT1022(Android 4.4.4 ,API 19).

**Comment by NileshJarad** [comment]
**FIXED**
 by adding `grantUriPermission(..)`

```
 activity.grantUriPermission(packageName, photoURI,
                        Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION); 
```
